#!/bin/bash

print_help () {
    echo "airlockctl v0.9.6

USAGE:
    airlockctl start   - starts the airlock control process
    airlockctl stop    - stops the airlock control process
    airlockctl restart - restarts the airlock control process
    airlockctl status  - returns the airlock status"
}

print_status () {
    [[ -f ~/.airlockctl ]] && cat ~/.airlockctl || echo 'Status: stopped'
}

start () {
    echo "Starting..."
    sleep 1
    curl -s $SPACEDINO_URL > /dev/null

    echo 'Status: running' > ~/.airlockctl

    echo "Success!"
}

stop () {
    echo "Stopping..."
    sleep 1
    echo 'Status: stopped' > ~/.airlockctl
}

case $1 in
    'start')
        echo "ERROR: please restart airlock system"
        exit 1
        ;;
    'stop')
        stop
        ;;
    'restart')
        stop
        start
        ;;
    'status')
        print_status
        ;;
    *)
        print_help
        ;;
esac