#!/bin/bash

for team in {1..2}
do
    docker run --name "airlock-$team" --restart=unless-stopped -d -p "222$team:22" --hostname=airlock -e PASSWORD=$(jq -r .[\"$team\"] < passwords.json) -e SPACEDINO_URL=https://starship.clb.li/airlock/start/$team airlock
done
