#!/bin/bash

start_container () {
    docker run \
    -d \
    --name "airlock-$1" \
    --hostname airlock \
    --restart unless-stopped \
    -p "222$1:22" \
    -e PASSWORD=$(jq -r .[\"$1\"] < passwords.json) \
    -e SPACEDINO_URL=https://starship.clb.li/airlock/start/$1 \
    airlock
}

for team in {1..4}
do
    start_container $team
done
